/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WalletRouteImport } from './routes/wallet'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ResolutionSlugRouteImport } from './routes/resolution.$slug'
import { Route as MarketSlugRouteImport } from './routes/market.$slug'

const WalletRoute = WalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResolutionSlugRoute = ResolutionSlugRouteImport.update({
  id: '/resolution/$slug',
  path: '/resolution/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketSlugRoute = MarketSlugRouteImport.update({
  id: '/market/$slug',
  path: '/market/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/wallet': typeof WalletRoute
  '/market/$slug': typeof MarketSlugRoute
  '/resolution/$slug': typeof ResolutionSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/wallet': typeof WalletRoute
  '/market/$slug': typeof MarketSlugRoute
  '/resolution/$slug': typeof ResolutionSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/wallet': typeof WalletRoute
  '/market/$slug': typeof MarketSlugRoute
  '/resolution/$slug': typeof ResolutionSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/wallet' | '/market/$slug' | '/resolution/$slug'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/wallet' | '/market/$slug' | '/resolution/$slug'
  id: '__root__' | '/' | '/wallet' | '/market/$slug' | '/resolution/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  WalletRoute: typeof WalletRoute
  MarketSlugRoute: typeof MarketSlugRoute
  ResolutionSlugRoute: typeof ResolutionSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wallet': {
      id: '/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof WalletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resolution/$slug': {
      id: '/resolution/$slug'
      path: '/resolution/$slug'
      fullPath: '/resolution/$slug'
      preLoaderRoute: typeof ResolutionSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/market/$slug': {
      id: '/market/$slug'
      path: '/market/$slug'
      fullPath: '/market/$slug'
      preLoaderRoute: typeof MarketSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  WalletRoute: WalletRoute,
  MarketSlugRoute: MarketSlugRoute,
  ResolutionSlugRoute: ResolutionSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
